# Generated by Django 4.2.29 on 2026-03-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve before farmers can see this dealer'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Red-flagged by admin based on complaints'),
        ),
    ]
