# Generated by Django 4.2.29 on 2026-03-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_dealer_is_approved_dealer_is_flagged"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dealer",
            index=models.Index(
                fields=["is_approved", "is_flagged"],
                name="core_dealer_is_appr_9e58b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dealer",
            index=models.Index(
                fields=["license_status"], name="core_dealer_license_b7f5e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealer",
            index=models.Index(
                fields=["trust_score"], name="core_dealer_trust_s_126d85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="core_order_status_6fe5d5_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["dealer"], name="core_order_dealer__4a1daa_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["farmer"], name="core_order_farmer__939a2a_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created_at"], name="core_order_created_929486_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["status"], name="core_report_status_4c7c3f_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["category"], name="core_report_categor_333d5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["dealer"], name="core_report_dealer__6ba1ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["-created_at"], name="core_report_created_a1bef3_idx"
            ),
        ),
    ]
